name: Terraform CI

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85  # v4.0.0
        with:
          terraform_version: 1.9.0

      - name: Terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform init (dev)
        run: terraform init -backend=false
        working-directory: terraform/environments/dev

      - name: Terraform validate (dev)
        run: terraform validate
        working-directory: terraform/environments/dev

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6  # v4
        with:
          tflint_version: v0.52.0

      - name: Run TFLint
        run: tflint --recursive
        continue-on-error: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@4048c972aae68d0b983a48bb3479aab2d877b898  # v12
        with:
          directory: terraform/
          framework: terraform
          quiet: true
          soft_fail: true
