name: Terraform CI

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform init (dev)
        run: terraform init -backend=false
        working-directory: terraform/environments/dev

      - name: Terraform validate (dev)
        run: terraform validate
        working-directory: terraform/environments/dev

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Run TFLint
        run: tflint --recursive
        continue-on-error: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          framework: terraform
          quiet: true
          soft_fail: true
